name: WorldDungeons
version: 1.0.4
main: fr.hillwalk.donjons.DonjonsMain
author: Hillwalk
api-version: 1.15
depend:
  - MythicMobs
  - WorldEdit
  - WorldGuard

commands:
  worlddungeons:
    description: Principal command.
    aliases: wd